### ISSUE TITLE
Four Phases == Too Much, Too Complicated

### ISSUE THREAD

**Issue by jnmclarty** [rexmls/whitepaper#1]
Hi All,

This is the first in a series of issues I plan to raise for this project.  Feel free to ignore me, until I get few posted.  They will start to tell a story.

I've paraphrase the four phases below, then added some commentary for each.

### Phase 1: global, decentralized, open source real estate database (RexCore). 

This is a massive problem, with massive impact, and many stakeholders and a variety of economic interests and incentives.  This alone, could be broken out into a 2 to 10 year plan.  It's extremely ambitious, especially at the global level?  Languages?  Units of measurements?  Purchasing Power Parity?  Government Intervention?  SPAM?   Do you want the Chinese Government to impact your Canadian Listings?  Do you want somebody in Mexico to be subject to the same spam/reward fees as a listing in New York?   

Making a public database that anybody can post to, and anybody can browse, of what are essentially a form of limit order, is going to have many challenges.

### Phase 2: Add filtration layer to the database using machine learning and human curation.

The curation part belongs as a sub phase for Phase 1.  I would argue, this team, doesn't need to worry about creating filters of any kind.  This team needs to worry about the listing service.  Let 2nd layers create user interfaces, and browsers, caches, and scrapers.

### Phase 3: real estate transaction services

There are already tons of people working on new economic models for exchanging goods and services. Why re-invent the wheel? If you think you need it, in order to make value for your token, so that Phase I can work - stay tuned, you don't.  Or shouldn't.  Or, at least, I don't think you should.

### Phase 4: Introduce Tokenized Ownership “liquid real estate”.

So you're going to make listings (effectively one side of an order book), then create the exchange?  And attempt to some how sell fractional shares of physical assets?  Blockchains are cool, but this is way too ambitious.  Crack Phase #1, disrupt an industry, then move on to tackle this after wards.

**Comment by rexmls** [comment]
Thanks jnmclarty, you are spot on, the four phases represent an incredible amount of work.. you are also correct in that phase 1 alone is a large enough challenge to keep us busy for quite a while.  

Our goal is very much aligned with what you have suggested, we are tackling the listings initially, and we expect and depend on phase 1 gaining popularity before moving onto the next phases.

Hence we are putting a lot of time and effort into outlining our mission for the upcoming token sale which we will use to grow the team and tackle some of these BIG challenges.
