### ISSUE TITLE
Users can sponsor major markets + Verification System + Professional Profiles ~= Legacy-System Like

### ISSUE THREAD

**Issue by jnmclarty** [rexmls/whitepaper#3]
This is the third issue, in a series of issues that will start to unveil a bit of a story.  Stay tuned.  Until then, see #1 & #2 in that order.

Getting to this section that started to dabble in how User's can sponsor major markets, and there's going to be a verification system based on "professionals" assuming a rate of 100:1, made me really sad.

If successful, we would just end up with monopolistic like forces, controlling real estate listings, the same way legacy systems do today.  Okay, it'd be a bit more distributed than the monopolies today, and maybe slightly more open.  But, if the people who got in early, prove to be incompetent (or even rational), and resources need to be spent rent seeking (sponsorship), then control and influence can be purchased, then up goes the costs for the people who matter: those who buy and sell real property.

**Comment by rexmls** [comment]
This is a great concern you have raised, i'll try cover our thoughts on the topic.

At its most fundamental, Rex the platform is about providing a global, standardized way for people to list their property for sale, which then allows people to search those listings and get in contact to make a deal.

This is an unstoppable feature of the platform, apart from requiring a very small amount of tokens which is purely to reduce spam users will always be able to post their listings.

The other part of the equation is we are trying to create a profitable business model to build and improve the platform, grow the team and make this a success so we have introduced the concepts of sponsoring markets and professional broker profiles etc.  These will be features of our proprietary software and if users would rather not participate then they are free to use the open source code and avoid the extra bells and whistles.

We want this platform to be as free and fair as much as anyone, we have gone to great lengths to ensure any options for profit dont interfere with the core premise of the platform.
