### ISSUE TITLE
Payment Delay, Registered "Listee", Banned Account == Insufficient, Unscalable

### ISSUE THREAD

**Issue by jnmclarty** [rexmls/whitepaper#4]
This is the last of four fairly critical posts I'm making for this project.  Over the coming days, I'll be shedding some light on opportunities with improvements to the economic and technical model, either privately or as new issues.  I await feedback from the maintainers to let me know which they prefer.

Simply close/delete these, if they are unwelcome; I can easily slink away.  See also #1, #2, #3.

I'm assuming some of the title logic is associated with SPAM protection, it's woefully inadequate.  

Your unregulated, unchecked central authority will be the king-pin with advanced insider knowledge about the market, while the rest of the market participants wade through 29-days of trash.

It won't scale to a network that costs orders of magnitude less than the legacy MLS systems.  It'll still be cheaper to operate, but it won't be infinitesimally cheap.  There will be moderation, censoring, false flag, related challenges galore.

**Comment by rexmls** [comment]
Hi jnmclarty, I only just stumbled across these issues.  Thanks for taking the time to raise some valid points.  I'll bring them up with the team and post some responses where appropriate.

**Comment by rexmls** [comment]
There will be very little central authority in operating the core platform, the only thing we will be doing is verifying the identities of users wishing to claim the listing rewards, we do this as its the only way to prevent it being gamed.

As this is an open source, peer 2 peer platform we expect the users to provide the majority of the spam filtering, and they will be rewarded for it by the platform.  I don't expect 29 days of trash listings, I expect trash listings to be flagged immediately and removed within days, I could be wrong, we may see some or a lot of listings remain the full 29 days, in which case we will review the gamification variables to improve things.

**Comment by jnmclarty** [comment]
>we do this as its the only way to prevent it being gamed.

Maybe it's the only way you can think of.  I doubt you've exhausted to universe of trustless ideas.

> we expect the users to provide the majority of the spam filtering

This might work for social networks, to an extent.  But where there is a large transaction on the line...there will be droves of bots attacking the network you're planning.
